"""
Module: AskAI.py
Purpose: AI-powered recommendations using Google Gemini
"""

import os
import sys
import re

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils.config import get_env

try:
    from google import genai
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False

_api_key = get_env('GEMINI_API_KEY')
_client = None
GEMINI_MODELS = ["gemini-2.5-flash", "gemini-2.0-flash", "gemini-2.5-pro"]


def get_cvss_severity(score):
    if score is None:
        return "Tidak tersedia"
    if score >= 9.0:
        return "Critical"
    elif score >= 7.0:
        return "High"
    elif score >= 4.0:
        return "Medium"
    elif score > 0:
        return "Low"
    return "None"


def format_tech_stack(tech_stack, affected_tech_name):
    others = [(name, ver) for name, ver in tech_stack if name != affected_tech_name]
    if not others:
        return None
    return ", ".join([f"{name} {ver}" if ver else name for name, ver in others])


def format_ai_response(text: str) -> str:
    text = re.sub(r'(?<!\n\n)(\n)?(📋|🔴|🛠️)', r'\n\n\2', text)
    text = re.sub(r'(?<=\S) (\d\.\s)', r'\n\1', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

def _get_client():
    """Get or create Gemini client."""
    global _client
    
    if not GEMINI_AVAILABLE:
        return None
    
    if not _api_key:
        return None
    
    if _client is None:
        _client = genai.Client(api_key=_api_key)
    
    return _client


def send_message(cve_id: str, cve_score, cve_description: str,
                 tech_name: str, tech_version: str, asset_name: str,
                 port, is_https, tech_stack: list):
    """
    Generate AI-powered vulnerability recommendation.
    
    Args:
        cve_id: CVE identifier
        cve_score: CVSS score (float or None)
        cve_description: CVE description from NVD/Vulners
        tech_name: Affected technology name (e.g., 'nginx')
        tech_version: Affected technology version (e.g., '1.18.0')
        asset_name: Host/asset name (e.g., 'example.com')
        port: Port number (int or None)
        is_https: Whether port is HTTPS (bool or int)
        tech_stack: List of (name, version) tuples for other techs on same service
        cve_description: CVE description
    
    Returns:
        Tuple of (recommendation_text, error_message)
    """
    client = _get_client()
    
    if not client:
        return None, "Gemini client not available. Check GEMINI_API_KEY."
    
    severity = get_cvss_severity(cve_score)
    score_display = f"{cve_score} ({severity})" if cve_score is not None else "Tidak tersedia"
    tech_display = f"{tech_name} {tech_version}" if tech_version else tech_name
    
    port_display = str(port) if port else "tidak diketahui"
    protocol = "HTTPS" if is_https else "HTTP"
    port_info = f"{port_display} ({protocol})"
    
    stack_info = format_tech_stack(tech_stack, tech_name)
    if stack_info:
        tech_stack_data = f"\nTech Stack (teknologi lain di port yang sama): {stack_info}\n"
        tech_stack_note = f"\nTech stack: {stack_info}. Pastikan kompatibilitas saat patch diterapkan."
    else:
        tech_stack_data = ""
        tech_stack_note = ""
    
    prompt = f"""Anda adalah Asisten Keamanan Siber. Berikan analisis kerentanan dalam Bahasa Indonesia.

--- DATA SUMBER ---
Aset: {asset_name}
Port: {port_info}
Teknologi Terdampak: {tech_display}
CVE ID: {cve_id}
Skor CVSS: {score_display}
Deskripsi: "{cve_description}"
{tech_stack_data}-------------------

STRICT OUTPUT FORMAT (IKUTI FORMAT INI PERSIS, GUNAKAN NEWLINE):

📋 APA INI?
[1 kalimat singkat, maksimal 30 kata]

🔴 3 RISIKO UTAMA:
1. [1 kalimat, maksimal 20 kata]
2. [1 kalimat, maksimal 20 kata]
3. [1 kalimat, maksimal 20 kata]

🛠️ PANDUAN PATCH (3 LANGKAH):
1. [WAJIB sebutkan versi aman: "Update {tech_name} dari versi {tech_version} ke versi X.X.X+", maksimal 25 kata]
2. [Langkah mitigasi alternatif, maksimal 25 kata]
3. [Langkah monitoring, sebutkan port {port_display} jika relevan, maksimal 25 kata]
{tech_stack_note}

CONTOH OUTPUT:

📋 APA INI?
Kerentanan XSS memungkinkan injeksi JavaScript berbahaya.

🔴 3 RISIKO UTAMA:
1. Pencurian cookie sesi pengguna.
2. Redirect ke situs phishing.
3. Defacement halaman website.

🛠️ PANDUAN PATCH (3 LANGKAH):
1. Update ke versi 2.1.0 atau lebih baru.
2. Tambahkan Content-Security-Policy header.
3. Monitor log di port 443 untuk pola XSS.

Tech stack: Node.js. Pastikan kompatibilitas saat patch.

PENTING: Setiap bagian harus di baris baru. Jangan gabungkan dalam satu baris. Ikuti contoh di atas persis."""
    
    last_error = None
    for model in GEMINI_MODELS:
        try:
            response = client.models.generate_content(
                model=model,
                contents=prompt
            )
            formatted = format_ai_response(response.text)
            return f"{formatted}\n\n_Generated by {model}_", None
        except Exception as e:
            last_error = str(e)
            print(f"Gemini API error ({model}): {e}")
            continue
    
    return None, "Gemini models unavailable or API key exhausted"


def compare_cve_details(desc_nvd: str, desc_vulners: str):
    """
    Compare two CVE descriptions for semantic match.
    
    Args:
        desc_nvd: NVD description
        desc_vulners: Vulners description
    
    Returns:
        True if match found, False otherwise
    """
    client = _get_client()
    
    if not client:
        return False, "Gemini client not available. Check GEMINI_API_KEY."

    prompt = f"""
    Role: Senior Security Auditor.
    
    Task: Determine if there is a MATCH or INCLUSION between the two descriptions.
    
    TEXT A:
    "{desc_nvd}"

    TEXT B:
    "{desc_vulners}"

    CRITICAL EVALUATION LOGIC (Follow in order):
    1. **ID MATCH (Silver Bullet):** Scan both texts for CVE IDs (e.g., CVE-2024-7347). 
       - If BOTH texts contain the SAME CVE ID, return 'True' IMMEDIATELY. 
       - Ignore the fact that one text might list other CVEs too.
       
    2. **SUBSET MATCH:** If one text is a list/advisory (containing multiple fixes) and the other text describes ONE of those fixes, return 'True'.
       - Example: Text A describes "Bug in MP4 module". Text B says "Fixes: Bug in MP4 module, Bug in HTTP module". -> Result: True.
       
    3. **SEMANTIC MATCH:** If no CVE IDs are present, check if they describe the same software (e.g., Nginx) AND the same component/issue (e.g., ngx_http_mp4_module memory corruption).

    OUTPUT: True or False only.
    """

    last_error = None
    for model in GEMINI_MODELS:
        try:
            response = client.models.generate_content(
                model=model,
                contents=prompt
            )
            
            if response and "true" in response.text.lower():
                return True, None
            return False, None
        except Exception as e:
            last_error = str(e)
            print(f"Gemini API error ({model}): {e}")
            continue
    
    return False, "Gemini models unavailable or API key exhausted"


if __name__ == '__main__':
    print("Testing AskAI...")
    print(f"Gemini API Key configured: {'Yes' if _api_key else 'No'}")
    print(f"Gemini available: {'Yes' if GEMINI_AVAILABLE else 'No'}")
    
    if _api_key and GEMINI_AVAILABLE:
        print("\nTesting send_message...")
        result, error = send_message(
            cve_id="CVE-2023-1234",
            cve_score=7.5,
            cve_description="A vulnerability in nginx allows remote attackers to cause a denial of service.",
            tech_name="nginx",
            tech_version="1.18.0",
            asset_name="test-server",
            port=443,
            is_https=True,
            tech_stack=[("Node.js", "18.0"), ("Express", "4.18")]
        )
        if result:
            print("Response received:")
            print(result[:500])
        else:
            print(f"No response received. Error: {error}")